name: cpu_temp_widget
author: 'Yuriy Yurinskiy'
email: yuriyyurinskiy@yandex.ru
url: https://yuriyyurinskiy.ru/
version: '0.1'
title: 'CPU Temp Widget'
icon: question
# dependency on Core is required for UI plugins
dependencies:
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: core
    }
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: dashboard
    }
resources:
    - 'resources/js/module.coffee'
    - 'resources/js/controllers/widget.controller.coffee'
    - 'resources/partial/widget.html'
    - 'ng:ajenti.cpu_temp_widget'